
# ======================================================================================================================
# QABASE CONFIGS
# ======================================================================================================================
qabase:
  core:
    reports:
      archive:
        enabled: false   # set to false (or omit) to disable