
# ======================================================================================================================
# QABASE CONFIGS
# ======================================================================================================================
qabase:
  rest:
    base-url: "https://jsonplaceholder.typicode.com"