
# ======================================================================================================================
# QABASE CONFIGS
# ======================================================================================================================
qabase:
  rest:
    base-url: "https://jsonplaceholder.typicode.com"
    headers:
      content-type: "application/json"
      accept: "application/json"
      authorization: "Bearer some-token"
