# SPRING
# ======================================================================================================================
#spring:
#  profiles:
#    active: "dev"

# CUSTOM APP
# ======================================================================================================================
rest-service:
  token: yourtokehere
  base-url: "https://jsonplaceholder.typicode.com"