# SPRING
# ======================================================================================================================
#spring:
#  profiles:
#    active: "dev"

# CUSTOM APP
# ======================================================================================================================
qabase:
  rest:
    base-url: "https://jsonplaceholder.typicode.com"